CREATE TABLE ACCOUNT
(
    ID                  CHAR(36) NOT NULL,
    NAME                VARCHAR(255),
    TRADING_ENVIRONMENT VARCHAR(32),
    CONSTRAINT CONSTRAINT_E PRIMARY KEY (ID)
);

ALTER TABLE ACCOUNT
    ADD CONSTRAINT CONSTRAINT_E4 UNIQUE (NAME, TRADING_ENVIRONMENT);