CREATE TABLE FILL
(
    PRICE       BIGINT,
    QTY         BIGINT,
    RECORDED_AT TIMESTAMP,
    ACCOUNT_ID  CHAR(36),
    CONTRACT_ID CHAR(36),
    ID          CHAR(36) NOT NULL,
    ORDER_ID    VARCHAR(255),
    TRADE_ID    VARCHAR(255),
    CONSTRAINT CONSTRAINT_2 PRIMARY KEY (ID)
);

ALTER TABLE FILL
    ADD CONSTRAINT CONSTRAINT_20 UNIQUE (TRADE_ID, ORDER_ID);