CREATE TABLE CONTRACT
(
    ID CHAR(36) NOT NULL,
    CONSTRAINT CONSTRAINT_C PRIMARY KEY (ID)
);

CREATE TABLE CONTRACT_REPRESENTATION
(
    CONTRACT_ID    CHAR(36)     NOT NULL,
    FORMAT         VARCHAR(255) NOT NULL,
    REPRESENTATION VARCHAR(255),
    CONSTRAINT CONSTRAINT_5 PRIMARY KEY (CONTRACT_ID, FORMAT)
);

ALTER TABLE CONTRACT_REPRESENTATION
    ADD CONSTRAINT CONSTRAINT_5E UNIQUE (FORMAT, REPRESENTATION);

ALTER TABLE CONTRACT_REPRESENTATION
    ADD CONSTRAINT FKRMJYDKB19UB13CW50GQIXTLCE FOREIGN KEY (CONTRACT_ID) REFERENCES CONTRACT (ID) ON DELETE NO ACTION;