CREATE TABLE EVENT_PUBLICATION
(
    COMPLETION_ATTEMPTS    INT      NOT NULL,
    COMPLETION_DATE        TIMESTAMP,
    LAST_RESUBMISSION_DATE TIMESTAMP,
    PUBLICATION_DATE       TIMESTAMP,
    ID                     CHAR(36) NOT NULL,
    EVENT_TYPE             VARCHAR(255),
    LISTENER_ID            VARCHAR(255),
    SERIALIZED_EVENT       VARCHAR(4000),
    STATUS                 VARCHAR(32),
    CONSTRAINT CONSTRAINT_EC PRIMARY KEY (ID)
);